// Scans assets/ and writes src/generated/asset-manifest.json (which files exist,
// so components can fall back to labelled placeholders) and MISSING_ASSETS.md.
// Runs automatically before studio, stills and renders.
import { readdirSync, statSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = join(ROOT, "assets");
const { merchants, audio } = await import(join(ROOT, "src/config.ts"));

const walk = (dir) =>
  readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [relative(ASSETS, p).split("\\").join("/")];
  });
const files = existsSync(ASSETS) ? walk(ASSETS).filter((f) => !f.split("/").pop().startsWith(".")).sort() : [];
const has = (f) => files.includes(f);

mkdirSync(join(ROOT, "src/generated"), { recursive: true });
writeFileSync(join(ROOT, "src/generated/asset-manifest.json"), JSON.stringify({ files }, null, 2) + "\n");

// Each expected asset lists the paths that satisfy it, preferred first.
const expected = [
  { what: "PRX Vault wordmark (lockup)", paths: ["brand/prx-logo.svg", "brand/prx-logo.png"] },
  { what: "PRX Vault icon (mark)", paths: ["brand/prx-logo-mark.svg", "brand/prx-logo-mark.png"] },
  { what: "Brand colours and fonts", paths: ["brand/brand.json"] },
  { what: "App home screenshot", paths: ["screens/app-home.png"] },
  { what: "App balance screenshot", paths: ["screens/app-balance.png"] },
  { what: "Music bed (optional)", paths: [audio.music], optional: true },
  ...merchants.map((m) => ({
    what: `Merchant logo: ${m.name}`,
    paths: [`merchants/${m.slug}.svg`, `merchants/${m.slug}.png`],
  })),
];

const missing = [];
const fallbacks = [];
for (const e of expected) {
  const found = e.paths.find(has);
  if (!found) missing.push(e);
  else if (found !== e.paths[0]) fallbacks.push({ ...e, found });
}

const lines = [
  "# Missing assets",
  "",
  "Generated by `npm run scan` (runs before every render). Do not edit by hand.",
  "",
  "## Missing (rendered as a grey placeholder with the file name on it)",
  "",
  ...(missing.filter((e) => !e.optional).length
    ? missing.filter((e) => !e.optional).map((e) => `- ${e.what}: \`assets/${e.paths[0]}\``)
    : ["- None"]),
  "",
  "## Optional, not supplied",
  "",
  ...(missing.filter((e) => e.optional).length
    ? missing.filter((e) => e.optional).map((e) => `- ${e.what}: \`assets/${e.paths[0]}\` (renders with a silent music bed)`)
    : ["- None"]),
  "",
  "## Using a fallback format",
  "",
  ...(fallbacks.length
    ? fallbacks.map((e) => `- ${e.what}: wanted \`assets/${e.paths[0]}\`, using \`assets/${e.found}\``)
    : ["- None"]),
  "",
  "## Known issues with supplied assets",
  "",
  "- PRX logos are raster only (2013x1053 lockup, 1053x1053 mark). They are sharp at this video size, but a vector export is needed to animate the wordmark letter by letter. Until then the wordmark reveals line by line (PRX, then VAULT) from the supplied PNG.",
  "- JD Sports and Superdry are in the design system's Merchant Banners, but their SVGs reference an embedded image that is empty, so they render blank. Both are left out of `config.ts` until working files are supplied.",
  "- The app screens are the design system's template screens, so they show placeholder content (\"John Smith\", \"$XX.XX\"). The balance callout covers the \"$XX.XX\" with the labelled example figure from `config.ts`.",
  "",
];
writeFileSync(join(ROOT, "MISSING_ASSETS.md"), lines.join("\n"));
console.log(`scan: ${files.length} asset files, ${missing.length} missing, ${fallbacks.length} fallbacks`);
